## Copyright 2018-present Network Optix, Inc. Licensed under MPL 2.0: www.mozilla.org/MPL/2.0/

version: "3"
services:
  mediaserver:
    build:
      context: .
      dockerfile: Containerfile
      args:
        COMPANY: ${COMPANY}
    # image: metavms-server:${MEDIASERVER_VERSION}
    user: ${COMPANY}
    ports:
      - ${PORTS}
    # To use the host network mode, comment out the ports above and uncomment the line below.
    # network_mode: "host"
    volumes:
      - ./config-volumes/etc:/opt/${COMPANY}/mediaserver/etc:z
      - ./config-volumes/var:/opt/${COMPANY}/mediaserver/var:z
      - ./config-volumes/nx_ini:/home/${COMPANY}/.config/nx_ini:z
      - ./config-volumes/entrypoint.d:/opt/mediaserver/entrypoint.d:z
      - ./config-volumes/recordings:/recordings:z
    tmpfs:
      - /tmp
