## Copyright 2018-present Network Optix, Inc. Licensed under MPL 2.0: www.mozilla.org/MPL/2.0/

version: "3"
services:
  mediaserver:
    build:
      context: .
      dockerfile: Containerfile
      args:
        COMPANY: ${COMPANY}
    image: metavms-server:${MEDIASERVER_VERSION}
    user: ${COMPANY}
    ports:
      - ${PORTS}
    # To use the host network mode, comment out the ports above and uncomment the line below.
    # network_mode: "host"
    volumes:
      - ${VOLUMES_PATH}/etc:/opt/${COMPANY}/mediaserver/etc
      - ${VOLUMES_PATH}/var:/opt/${COMPANY}/mediaserver/var
      - ${VOLUMES_PATH}/nx_ini:/home/${COMPANY}/.config/nx_ini
      - ${VOLUMES_PATH}/entrypoint.d:/opt/mediaserver/entrypoint.d
      - ${VOLUMES_PATH}/recordings:/recordings
    tmpfs:
      - /tmp
